Allow #![] attributes to work in 0.16
lalrpop/lalrpop pull request #384
Opened 2018-06-17 04:19 UTC by wycats

In 0.16, the default mode for lalrpop will import the generated module
through a macro that `include!`s the contents.

PR #338 made it possible to use `include!` with vanilla modules by
moving all of the built-in whole-module attributes to individual
modules. However, #115 places user-generated outer attributes in the
same problematic location.

This PR moves user-supplied outer attributes to the same location as
the fix in #338.

2018-06-19 08:28 UTC, nikomatsakis requested changes
I have some concerns about this change -- it feels surprising to emit the module attributes also on the internal modules. Maybe we should add some kind of explicit Edition support, if that is the main motivation?

2018-06-19 08:28 UTC, nikomatsakis commented on lalrpop-snap/src/rust/mod.rs
> -    pub fn write_module_attributes(&mut self, grammar: &Grammar) -> io::Result<()> {
we don't usually edit lalrpop-snap

2018-06-19 08:28 UTC, nikomatsakis commented on lalrpop-snap/src/build/mod.rs
> +pub fn emit_module_attributes<W: Write>(
we don't typically edit lalrpop-snap

2018-06-19 08:28 UTC, nikomatsakis commented on lalrpop/src/build/mod.rs
> +    rust!(rust, "#[cfg_attr(rustfmt, rustfmt_skip)]");
Something feels fishy about this. This attribute is going to apply to the *next* module thing that gets emitted ... oh, I see, and the for loop below is intentionally converting `#![foo]` into `#[foo]`?

2018-06-19 08:30 UTC, nikomatsakis commented
OK, re-reading your comment, I think I understand better. So there are two distinct things going on here:

- Converting `#![foo]` to `#[foo]` -- this may indeed be a good idea, given the problems around `#![]` attributes and `include!` (IIUC)
- Apply those attributes to all the generated submodules -- I'm less sure about this, but it *may* make sense? I'm not sure if there was a direct motivation for this.

2018-06-19 08:31 UTC, nikomatsakis commented
Ah, probably we apply the attributes to the submodules just because it's not obvious how to apply them .. otherwise?

2018-06-19 09:11 UTC, Marwes commented
> Ah, probably we apply the attributes to the submodules just because it's not obvious how to apply them .. otherwise?

Yep. https://github.com/rust-lang/rust/issues/18810

2018-08-31 18:42 UTC, Marwes commented
Thinking about it, perhaps we could wrap the generated module as

```
mod name {
    #![attr]
     // Rest of the code goes here
}
pub use name::{Parser, ..};
```

2019-01-17 06:21 UTC, alercah commented
Personally I think I'm inclined to the `mod_path!` workaround, because it allows attaching other attributes from the outside too:

```rust
#[deny(...)]
lalrpop_mod!(...);
```

2019-04-22 20:44 UTC, franleplant commented
Hi guys! I have a question, https://github.com/lalrpop/lalrpop/issues/115 allegedly allowed attributes in top of the grammar file, I tried with 0.16.x and it doesnt work, and then I see this PR. 

From what I understand, and, as a nice recap for future people, did this feature broke on 0.16.x and that is why this PR exists?

2019-10-28 22:22 UTC, franleplant commented
@nikomatsakis how about adding by default a `#[allow(clippy::all)]` to the synthesized module?

2020-04-23 13:47 UTC, NyxCode commented
For everyone who stumbled upon this issue:
the `lalrpop_mod!` macro can accept attributes like this: `lalrpop_mod!(#[allow(clippy::all)] grammar);`

2026-07-15 01:41 UTC, wycats commented
Closing this 0.16-era implementation. The codebase and maintainer direction have moved on substantially; if the need remains, it should be reconsidered against current master.

2026-07-15 01:41 UTC, closed without merging